### ISSUE TITLE
Review du TP

### ISSUE THREAD

**Issue by tancou** [PolytechLyon/2019-isi3-graph-suard_thomas#15]
Bonjour,

Voici une première version de ce qui nous semble être le TP fini.
Dans l'attente de votre retour.

**Comment by Slashgear** [comment]
- 👍 Rapport
- [ ] Vous utilisez des `parallelStream`, pouvez vous m'expliquer ici comment ceux-ci fonctionnent ? 😉 
- Sinon 👍 Itérateur et Adapter

**Comment by tancou** [comment]
Merci pour le retour rapide.

Nous avons décidé d'utiliser les ``parallelStream`` au lieu d'un ``stream`` pour les deux map dans le ``toString()`` de la classe ``Graph`` parce que chaque opération qu'on applique sur les éléments est en réalité des opérations sur des strings, de manière indépendante. Ces opérations peuvent donc se faire indépendamment en parallèle. De plus, plus il y a de nœud et d'arcs et plus ce choix sera visible en temps d’exécution (mais sans doute un peu plus gourmand en mémoire).

Cette fonction permet d'itérer sur chacun des éléments en parallélisant dans une pool de thread chaque opération. C'est complètement invisible pour le développeur. Le calcul des threads est non déterministe, on ne sait pas dans quel ordre les données sont traitées, toutefois, le résultat est déterministe étant donné qu'une fois tous les threads terminés, le ``collect`` remet en ordre les éléments. (Ici dans notre cas, les données seront concaténées dans l'ordre avec le ``join``).
Le seul inconvénient de cette fonction est dans le cas où les calculs itérés sont longs ou dépendants d'autres facteurs. Dans ce cas, c'est toute la pool de Thread qui passe en attente que le Thread le plus lent soit terminé. Ce qui peut clairement être un désavantage suivant l'implémentation. Dans le cas où plus de Threads sont lents qu'il n'y a de coeurs processeur disponibles sur la machine (ou alloués au logiciel).
